name: Build

on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install --legacy-peer-deps
    - run: npm run build
    - name: Install zip
      uses: montudor/action-zip@v1
    - name: package
      working-directory: dist/lethean-desktop/browser
      run: zip -qq -r ../../../lethean-ui.zip .
    - uses: actions/upload-artifact@v2
      with:
        name: lethean-ui
        path: lethean-ui.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: lethean-ui.zip
  lauchers:
    name: "Trigger: letheanVPN/desktop"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: build
          repository: letheanVPN/desktop




